server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 01
    host: 119.45.115.231
    password: IJPay
    port: 6379
    timeout: 5000d
    lettuce:
      pool:
        #连接池的最大数据库连接数（设为0表示无限制）
        max-active: 8
        #连接池中的最大空闲连接，默认值是8。
        max-idle: 8
        #连接池中的最小空闲连接，默认值是0。
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
      shutdown-timeout: 100ms
